// Imports the Inter font from Google Fonts using the new font optimization feature in Next.js.
import { Inter } from "next/font/google";
// Imports global CSS styles that will be applied throughout the application.
import "./globals.css";

// Initializes the Inter font with specific subsets (in this case, "latin"). This optimization helps to reduce loading times by only loading the character sets you need.
const inter = Inter({ subsets: ["latin"] });

// Exports metadata for the application, which could be used for SEO or by other components in the app to display or use the application's title and description dynamically.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Defines the default export of the file, which is a RootLayout component. This component is a functional component that takes in `children` as a prop.
export default function RootLayout({ children }) {
  return (
    // Returns an HTML structure starting with the `<html>` element, specifying the language of the document.
    <html lang="en">
      {/* The `<body>` element uses the `className` provided by the `inter` font object, which includes the necessary styles for the Inter font. */}
      <body className={inter.className}>
        {/* Renders the children inside the body. This allows the RootLayout to wrap around other components or page content, effectively applying the layout's styles and structure to them. */}
        {children}
      </body>
    </html>
  );
}
